feat(intermediario): Detalha o material sobre variáveis CSS
mathh95/css4noobs pull request #46
Opened 2023-08-01 03:28 UTC by Allyhere

Aprofunda o material, cria uma estrutura de tópicos e fornece mais exemplos.

Relacionado à issue #22

2023-08-01 22:50 UTC, RodrigoRVSN approved these changes

2023-10-04 18:38 UTC, gitlherme requested changes

2023-10-04 18:38 UTC, gitlherme commented on Modulo-Intermediario/variables.md
> +Variáveis CSS são entidades definidas por nós desenvolvedores, contendo valores que irão ser utilizados em todo o nosso projeto. Utilizamos o `var(<variavel>)` para indicar que estamos chamando uma v
Podemos trocar de desenvolvedores para pessoas desenvolvedoras.

2023-10-04 21:00 UTC, SamucaDev commented
@Allyhere podemos avaliar este PR? ou prefere fazer alterações

2023-10-04 22:11 UTC, Allyhere commented
> @Allyhere podemos avaliar este PR? ou prefere fazer alterações

@SamucaDev, uma vez aprovado o PR anterior a respeito da sugestão de reestruturação eu vou aproveitar a oportunidade pra rever esse texto aqui, hoje eu tenho mais informações do que quando escrevi, tudo bem?

Ai eu já corrijo essa questão https://github.com/he4rt/css4noobs/pull/46#discussion_r1346305597

2023-10-04 22:32 UTC, SamucaDev commented
Perfeito @Allyhere vamos focar em avaliar este https://github.com/he4rt/css4noobs/pull/47 .

2023-10-11 18:36 UTC, closed without merging